project_id = "dpgvanocynbrmqvgvgvd"

[functions.send-contact-email]
verify_jwt = false

[functions.send-mediakit-email]
verify_jwt = false

[functions.calendar-feed]
verify_jwt = false

[functions.yt-search]
verify_jwt = false

[functions.yt-ingest]
verify_jwt = false

[functions.yt-cron]
verify_jwt = false

[functions.script-version]
verify_jwt = false
